name: todoapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  get: 4.5.1
  flutter_local_notifications: ^8.2.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  google_fonts: ^2.1.0
  date_picker_timeline:
  sqflite: ^2.0.0+4
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  flutter_launcher_icons: ^0.9.2
  rxdart: ^0.27.2
  animated_splash_screen:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:



flutter_icons:
  android: true
  ios: true
  image_path: "images/todo.jpeg"



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
